INSERT INTO weddings (name, essentials, amount) VALUES ('Wedding Dress', true,12000.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Flowers', false, 1100.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Invitations', true, 1500.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Rental of Venue', true, 1600.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Hourly DJ', true, 200.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Hourly Photographer', true, 250.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Decorations', false, 150.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Honey Moon', true, 1,000.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Wedding Viel', true, 150.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Gifts for Guests', false, 300.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Cake', true, 300.00);
INSERT INTO weddings (name, essentials, amount) VALUES ('Catering', true, 600.00);
